# Generated by Django 5.0.6 on 2024-05-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="pastmessages", name="messages",),
        migrations.AddField(
            model_name="pastmessages",
            name="mamba_messages",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="pastmessages",
            name="user_messages",
            field=models.TextField(default=""),
        ),
    ]
