# Generated by Django 5.0.6 on 2024-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_pastmessages_messages_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pastmessages",
            old_name="creation_date",
            new_name="date_modified",
        ),
        migrations.RemoveField(model_name="pastmessages", name="mamba_messages",),
        migrations.RemoveField(model_name="pastmessages", name="user_messages",),
        migrations.AddField(
            model_name="pastmessages",
            name="messages",
            field=models.JSONField(default={}),
        ),
    ]
