# Generated by Django 5.0.6 on 2024-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_creation_date_pastmessages_date_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastmessages",
            name="messages",
            field=models.JSONField(default=dict),
        ),
    ]
