# Generated by Django 5.0.6 on 2024-05-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_pastmessages_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastmessages",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
